### ISSUE TITLE
I want  libassimp.so only

### ISSUE THREAD

**Issue by AIM54** [kenomo/assimp-for-android#2]
I want to get  some .so files such as libassimp.so, but  after compile the sorce code i get  libassimp.so、libassimp.so.5、libassimp.so.5.0.1. My building environment is Ubuntu 19.0.4 and ndk  version is 21

**Comment by kenomo** [comment]
libassimp.so and libassimp.so.5 are soft links on libassimp.so.5.0.x, so use libassimp.so.5.0.x or rename it.
